---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role-config-map
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - "cluster-monitoring-config"
      - "user-workload-monitoring-config"
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
