---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  - apiGroups:
      - monitoring.arthurvardevanyan.com
    resources:
      - clusters
      - users
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - monitoring.arthurvardevanyan.com
    resources:
      - clusters/finalizers
      - users/finalizers
    verbs:
      - update
  - apiGroups:
      - monitoring.arthurvardevanyan.com
    resources:
      - clusters/status
      - users/status
    verbs:
      - get
      - patch
      - update
