apiVersion: monitoring.arthurvardevanyan.com/v1beta1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/name: cluster
    app.kubernetes.io/instance: cluster-sample
    app.kubernetes.io/part-of: openshift-monitoring-cr-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: openshift-monitoring-cr-controller
  name: cluster-sample
spec:
  prometheusK8s:
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: prometheus
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: prometheus
