apiVersion: monitoring.arthurvardevanyan.com/v1beta1
kind: User
metadata:
  labels:
    app.kubernetes.io/name: user
    app.kubernetes.io/instance: user-sample
    app.kubernetes.io/part-of: openshift-monitoring-cr-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: openshift-monitoring-cr-controller
  name: user-sample
spec:
  prometheus:
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: prometheus
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: prometheus
